# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fabrício Silva
name: Fabrício Silva
description: > # this means to ignore newlines until "baseurl:"
  Web developer focused in front-end
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fabriciofmsilva.com.br" # the base hostname & protocol for your site
domain: fabriciofmsilva.com.br
lang: pt-BR

reading_time: true
words_per_minute: 200

permalink: /:title/

author: Fabrício Silva
github: https://github.com/fabriciofmsilva
twitter: https://twitter.com/fabriciofmsilva
linkedin: https://www.linkedin.com/in/fabriciofmsilva
plus: https://plus.google.com/+FabricioFMSilva
feedburner: https://feeds.feedburner.com/fabriciofmsilva
analytics: UA-22890269-1

collections:
  - projects

# Build settings
markdown: kramdown

# gems
gems:
  - jekyll-sitemap
  - jekyll-toc

# sass
sass:
  sass_dir: _sass

# Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed/
excerpt_separator: ""
